"use client";
import type { Metadata } from "next";
import { Anton, Montserrat } from "next/font/google";
import "./globals.css";
import AppProvider from "@/providers/AppProvider";
import UserProfiles from "@/components/ui/UserProfiles";
import { ToastContainer } from "react-toastify";
import { usePathname } from "next/navigation";
import "react-toastify/dist/ReactToastify.css";
import Header from "@/components/ui/Header";
import Footer from "@/components/ui/Footer";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const anton = Anton({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-anton",
});

// export const metadata: Metadata = {
//   title: "Chat App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${anton.variable}`}>
        <AppProvider>
          <ToastContainer />
          <Header />
          <main>{children}</main>
          {pathname == "/chatApp" ? "" : <Footer />}
        </AppProvider>
      </body>
    </html>
  );
}
